notifications:
  email: false
language: node_js
node_js:
- 6.9.1
- node
sudo: false
before_script:
- npm run lint
- npm run build
before_install:
- npm install buffer-shims
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- npm install
before_deploy:
- node ./write-version.js
- npm run build
- "./deploy-sourcemaps.sh"
after_success: npm run coveralls
deploy:
- provider: npm
  skip_cleanup: true
  email: admin@inspirehep.net
  api_key:
    secure: afzLZGZlvOC4zMrZon9H7iTDcVuH5j+fDt4LmP+wm2jLm7Fg9yY2XKIO0psTOwl3Gy/Ej1L9aMab1uRObLp2YgvqcpCWmXKvoWMrnIimcyJPXuQGYflF3GKunoGlSWBD9/76+Ggj5ml26ksUJXOx6NDNhjYRd4jatGQ04ISdkARm7lWPdDQ1S1yKAZLQ2oPFtJKZ9Kq8b7LV95I7YHa2u0r4mi36V3ap++jK7n8s1LQvtgDPky7W1CKfpO29r2Zb69fwo5FJxjdibyJDRuBkuYbyUsNMvCPnxIHduyr5S7yyxU+6wM+CIkVEk/pAbe50xmW5jpEEq+5YlaQVQTvo2lJBZnYh8FsZHVMG78kmDzCwhSstSkQcTEAmQGxlUNwi96DcGAj7e7QNGUyRXbXQhCBy6s900dl8b9J6QQ+gNrsJi8VNE++P13S8EOMoUDc0MH+CsywuIWejnTeyTMr5kuOn/tfQan23N/DZ/A+9HnTs66ZWQOnm8R8vF6gB74QKFwH4pR6rdPC448q9M4qz0GVCt6jRceTgZB88833FI9qPk6IBcREFGLtOlITptItuOG7VniHOVHB1W1j0JIgCF22zFyH7KoWKILC5WF5GG8Uopq7rX0k+BcAsfeiWWCvnqry8yCAaqUtszhYUMB0TH03OlFoyOlDGPZS8OfrHji8=
  on:
    tags: true
    repo: inspirehep/record-editor
    all_branches: true
    node: 6.9.1
- provider: npm
  skip_cleanup: true
  email: admin@inspirehep.net
  api_key:
    secure: afzLZGZlvOC4zMrZon9H7iTDcVuH5j+fDt4LmP+wm2jLm7Fg9yY2XKIO0psTOwl3Gy/Ej1L9aMab1uRObLp2YgvqcpCWmXKvoWMrnIimcyJPXuQGYflF3GKunoGlSWBD9/76+Ggj5ml26ksUJXOx6NDNhjYRd4jatGQ04ISdkARm7lWPdDQ1S1yKAZLQ2oPFtJKZ9Kq8b7LV95I7YHa2u0r4mi36V3ap++jK7n8s1LQvtgDPky7W1CKfpO29r2Zb69fwo5FJxjdibyJDRuBkuYbyUsNMvCPnxIHduyr5S7yyxU+6wM+CIkVEk/pAbe50xmW5jpEEq+5YlaQVQTvo2lJBZnYh8FsZHVMG78kmDzCwhSstSkQcTEAmQGxlUNwi96DcGAj7e7QNGUyRXbXQhCBy6s900dl8b9J6QQ+gNrsJi8VNE++P13S8EOMoUDc0MH+CsywuIWejnTeyTMr5kuOn/tfQan23N/DZ/A+9HnTs66ZWQOnm8R8vF6gB74QKFwH4pR6rdPC448q9M4qz0GVCt6jRceTgZB88833FI9qPk6IBcREFGLtOlITptItuOG7VniHOVHB1W1j0JIgCF22zFyH7KoWKILC5WF5GG8Uopq7rX0k+BcAsfeiWWCvnqry8yCAaqUtszhYUMB0TH03OlFoyOlDGPZS8OfrHji8=
  tag: dev
  on:
    repo: inspirehep/record-editor
    branch: dev-release
    node: 6.9.1
env:
  global:
    secure: mK3rPSEzCLX4LONWTXlvVm3BtdqoKNJziJnsNiy4FPoxPn8XX8GpNreN+l6+y1/Uq8AjI56CsGbDlXkrPO5+wkCBAUdtI8bjfAXsQ+TSoBbizBMR6Y/4DNHh5+tlLbL0QnAos053+Obi21LP7Oxqih5zu5OectHzL8Vos+Z+mDho0gqOtZxl4d2P2/lG8vmW+4whwqQ+C0LraSP+uuAcWh3MWUaaVyIeNYQs5RbfSoLyGNueUTpG68YZhQ/uv+Ov2dyozRxGETTW8YZ3tjuxdqcY62Gb6cMRSeghIxjsiqBDWmOw50wJma4GonOZmwj/rl3ba3Mf/Ogc+Xv6Q2onj4d7zDHCU4XbwNymSjyHgnc7vbpvb5xy/609c3TaBxkIhz2lNWFyQXjl+GEqi5Bq/u7JV4UjDroBRBugpq96WghRhbxcDgOHDaDMT7Qjoyx4JhfqJmX7ZtdV209hGdIDFdjCR+sIimeWRjMhKfv1AI5GQvpGMv3QW3ddLCU6/9S2Cmw+cqtSCGgj9YPyN8qb4rYRtG4IFPsXbZNuxY1Vc24+kBqSAuTxYST+N5IlWd1XXSM5kHdTaSTwxcF76pJn9lLIPfikUK+pcvG/tgLG/hbCuYKXj1J2e5ObZU39sl6gExqZkrMgQ8mdOUkSVna5tJpeI/Moh/eDUmjadIxYg5o=
